- name: Looping through items
  hosts: localhost
  tasks:
    - name: Print each item with debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "Apple"
        - "Banana"
        - "Cherry"
