- name: Looping through items
  hosts: localhost
  tasks:
    - name: Print each item with debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "Apple"
        - "Banana"
        - "Cherry"

- name: Demo task with dictionary in loop
  hosts: localhost
  tasks:
    - name: Print name and quantity
      ansible.builtin.debug:
        msg: "Item: {{ item.name }}, Quantity: {{ item.quantity }}"
      loop:
        - {name: "Apple", quantity: 10}
        - {name: "Banana", quantity: 20}
        - {name: "Cherry", quantity: 30}

