- name: Looping through items
  hosts: localhost
  tasks:
    - name: Print each item with debug
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "Apple"
        - "Banana"

- name: Demo tasks for loop
  ansible.builtin.debug:
    msg: Friut Name - {{ item.name }}, Quantity - {{ item.quantity }}, {{item.name }}
  loop:
    - {name: Apple,quantity: 10}
    - {name: {Banana, quantity: 20}
